-- SPDX-License-Identifier: Apache-2.0
PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS objects (
  cid TEXT PRIMARY KEY,
  bytes BLOB NOT NULL
);
CREATE TABLE IF NOT EXISTS events (
  seq INTEGER PRIMARY KEY,
  cid TEXT NOT NULL UNIQUE REFERENCES objects(cid),
  previous_cid TEXT REFERENCES objects(cid),
  request_key TEXT NOT NULL UNIQUE,
  request_digest TEXT NOT NULL
);
CREATE TRIGGER IF NOT EXISTS objects_no_update BEFORE UPDATE ON objects
BEGIN SELECT RAISE(ABORT, 'APPEND_ONLY'); END;
CREATE TRIGGER IF NOT EXISTS objects_no_delete BEFORE DELETE ON objects
BEGIN SELECT RAISE(ABORT, 'APPEND_ONLY'); END;
CREATE TRIGGER IF NOT EXISTS events_no_update BEFORE UPDATE ON events
BEGIN SELECT RAISE(ABORT, 'APPEND_ONLY'); END;
CREATE TRIGGER IF NOT EXISTS events_no_delete BEFORE DELETE ON events
BEGIN SELECT RAISE(ABORT, 'APPEND_ONLY'); END;
